.travis.yml
main.ml

This is related to [djs55/xapi-storage#13]

Implement SR.stat

---

main.ml

Implement VDI.stat -> Volume.stat

---

main.ml

Automatically add capabilities if a plugin file is present

---

main.ml

Signed-off-by: David Scott <dave.scott@eu.citrix.com>

Plumb through physical_utilisation from Volume.stat

---

main.ml

This depends on [xapi-project/xcp-idl#80]
Signed-off-by: David Scott <dave.scott@eu.citrix.com>

Invoke Volume.set_name and Volume.set_description

---

main.ml

Pass through any Volume.uuid to the SMAPIv2

---

main.ml

Plumb through SR.destroy

---

main.ml

This is simply passed-through to the SMAPIv2.

Add support for `required_cluster_stack`

---

README.md

Signed-off-by: David Scott <dave@recoil.org>

Add link to docs to README.md

---

main.ml

This needs to be merged at the same time as
- [xapi-project/xcp-idl#90]
- [xapi-project/xapi-storage#48]

CP-13525: plumb through SR.probe

---

main.ml

CP-13874: plumb through SR `name_label` and `name_description`

---

main.ml

Plumb through the `SR.create` name and description

---

.travis.yml
main.ml
opam

Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>

Update to newer core release

---

main.ml

Signed-off-by: Rob Hoes <rob.hoes@citrix.com>

CA-222845: Create dir for state_path proactively

---

main.ml

Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

CP-22446: Add cbt_enabled=false field to vdi_of_volume to fix compilation

---

main.ml

Needs to be merged after/together with https://github.com/xapi-project/xapi-storage/pull/68
Jenkins test pending

CA-277837: plumb through uuid for SR.attach

---

main.ml
xapi-storage-script.opam

This is part of the `opam/next` patches

[opam/next] Update to support core/async >= v0.9.0

---

main.ml

Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

Changes after adding SR UUID to sr_info in xcp-idl

---

.travis.yml
jbuild
main.ml
xapi-storage-script.opam

Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

CA-283693: Store & return correct snapshot_time for VDIs

---

jbuild
main.ml

Updated @jonludlam's [PR](https://github.com/xapi-project/xapi-storage-script/pull/64) with requested changes.

CP-26583: Update with PPX-based RRDD changes

---

jbuild
xapi-storage-script.opam

This has to go in with https://github.com/xapi-project/xs-opam/pull/266

Use the new rpc.5.0.0 and rpclib-legacy

---

main.ml

Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

CA-290241: save VDI's is_a_snapshot & snapshot_of fields

---

.travis.yml
jbuild

Signed-off-by: Christian Lindig <christian.lindig@citrix.com>

Simplify PPX processing in jbuild file

---

main.ml

Use PPX Storage IDL rather than Camlp4

Storage PPX

---

main.ml

Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>

New ocaml-rpc

---

main.ml

We now honour the existing API of Datapath.attach by
passing the domid of vm that the vbd is being attached to.
This will enable a qemu process per vm.
Signed-off-by: ben sims <ben.sims@citrix.com>

CP-31450: Add domid to Datapath.attach

---

.travis.yml
main.ml

Signed-off-by: Christian Lindig <christian.lindig@citrix.com>

Fix Stdlib warning
